feat(theme): update theme for button
Availity/element pull request #13
Opened 2023-02-27 19:31 UTC by bjnewman

feat(theme-provider): fix theme type

2023-02-27 20:13 UTC, LauRoxx commented on apps/element-storybook/src/theme-provider.stories.tsx
> +    <div>This component is outside the ThemeProvider</div>
my changes will be putting every story in a ThemeProvider so this will still be styled.

2023-03-01 15:24 UTC, jordan-a-young requested changes
Looks great! Just had one comment about removing a dep

2023-03-01 15:24 UTC, jordan-a-young commented on packages/button/package.json
> +    "@mui/material": "^5.11.6"
We can remove this since it's listed as a dev and peer dependency

2023-03-01 16:13 UTC, jordan-a-young approved these changes

2023-03-01 16:20 UTC, merged